### ISSUE TITLE
Showing Fully Synced while blockchain needs syncing about 50k blocks more

### ISSUE THREAD

**Issue by himu007** [Meshbits/Shurli#28]
Displaying fully synced PIRATE while the daemon is still syncing about 50k more blocks.

![shurli](https://user-images.githubusercontent.com/8881040/86831376-b99a2f00-c08e-11ea-850f-c164604bcaa1.png)

Shurli collects info from `getblockchaininfo`. Here is the output:
```
{
  "chain": "main",
  "blocks": 924645,
  "synced": false,
  "headers": 963585,
  "bestblockhash": "000000009cadd16bde572f430b23bd99720da063bda98d0444859f5cf1bad662",
  "difficulty": 183010772.2203555,
  "verificationprogress": 0.9595884120238485,
```
Has to make an improvement on this math part. Maybe `verificationprogress` can use `0.99xxx` progress as synced as we had issues with this using KomodoOceanQT wallet.

**Comment by Noah-svg** [comment]
自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。一般像优盾钱包这类企业钱包开放平台，通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是boss在客户端上管理，服务器上不存。

**Comment by satindergrewal** [comment]
@himu007 I have pushed update with the commit https://github.com/Meshbits/Shurli/commit/972aa226c9616a811c0bd8d65b6bfd294e52f644

Seems to be behaving fine in my local tests.
Please check and close this issue if it's fixed in your tests too.
